# Welcome to Jekyll!


# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: Est-ce que c'est du travail ?
description: Documentation d'itinérance
owner:
  name: Thomas Parisot et Noémie Girard
  email: hello@estcequecestdutravail.xyz
  url: https://estcequecestdutravail.xyz
first_published: 2018
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://estcequecestdutravail.xyz" # the base hostname & protocol for your site
timezone: Europe/Paris

twitter:
  image: /images/2018-03-05-voir-londres-et-partir/Auriga sacs.jpg

seo_tag:
  image: /images/2018-03-05-voir-londres-et-partir/Auriga sacs.jpg

# - title for your blog's featured posts
features-title: Featured articles
# - displayed at the bottom
closing-head: À&nbsp;bientôt&nbsp;😀
closing-para:

# on all pages (and the first three you list display with greeting, if included)
social:
  twitter: https://twitter.com/noeems
  github: https://github.com/noeems/estcequecestdutravail.xyz
  email: mailto:hello@estcequecestdutravail.xyz

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:year/:month/:slug:output_ext
markdown: kramdown
sass:
 style: compressed

exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']

plugins:
- jekyll-avatar
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-feed

defaults:
- scope:
    path: ""
  values:
    image: /images/2018-03-05-voir-londres-et-partir/Auriga sacs.jpg
- scope:
    path: _pages
  values:
    layout: page
    #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
- scope:
    path: _posts
  values:
    layout: post
- scope:
    path: _drafts
  values:
    layout: post

collections:
- itineraries

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
